### ISSUE TITLE
Error when packaging with PyInstaller

### ISSUE THREAD

**Issue by maicol07** [UN-GCPDS/pyside-material#4]
Getting this error when opening a script packaged with [pyinstaller](pyinstaller.org):

```
Traceback (most recent call last):
 File "main.py", line 25, in <module>
 File "c:\users\maicol\.conda\envs\modpack_sphaxifier\lib\site-packages\pyside_material\__init__.py", line 158, in list_themes
   os.path.dirname(os.path.abspath(__file__)), 'themes'))
FileNotFoundError: [WinError 3] Can't find the specified path: 'D:\\Maicol\\Documents\\Progetti\\Windows\\Modpack_Sphaxifier\\dist\\main\\pyside_material\\themes'
```

It seems that `__file__` returns the current script, not pyside-material script

**Comment by maicol07** [comment]
It seems that you need to add the themes folder as data to pyinstaller bundle
